/**
 * Typography scale based on the golden ratio (φ ≈ 1.618)
 *
 * Font sizes are generated by raising φ to various powers, creating
 * a harmonious progression where each size relates to others through
 * the golden ratio.
 *
 * This creates clear visual hierarchy with mathematically pleasing proportions.
 */

import type { FontSizeKey, LineHeightKey, LetterSpacingKey } from '../core/types';
import { PHI } from '../core/constants';

/**
 * Font size scale in rem units
 * Each step is φ times the previous (base = 16px)
 */
export const fontSize: Record<FontSizeKey, string> = {
  xs: '0.618rem',    // ~10px  (base / φ²)  - Fine print, captions
  sm: '0.809rem',    // ~13px  (base / φ)   - Small text, labels
  base: '1rem',      // 16px   (base)       - Body text
  lg: '1.618rem',    // ~26px  (base × φ)   - Subheadings
  xl: '2.618rem',    // ~42px  (base × φ²)  - Headings
  '2xl': '4.236rem', // ~68px  (base × φ³)  - Large headings
  '3xl': '6.854rem', // ~110px (base × φ⁴)  - Display text
  '4xl': '11.089rem',// ~177px (base × φ⁵)  - Hero text
  '5xl': '17.942rem',// ~287px (base × φ⁶)  - Massive display
} as const;

/**
 * Type-safe font size keys
 */
export type FontSizeKeys = keyof typeof fontSize;

/**
 * Font sizes in pixels (for reference)
 */
export const fontSizePx: Record<FontSizeKey, number> = {
  xs: 9.888,
  sm: 12.944,
  base: 16,
  lg: 25.888,
  xl: 41.888,
  '2xl': 67.776,
  '3xl': 109.664,
  '4xl': 177.424,
  '5xl': 287.088,
} as const;

/**
 * Line height scale based on golden ratio relationships
 *
 * These values create comfortable reading while maintaining
 * mathematical harmony with the overall system.
 */
export const lineHeight: Record<LineHeightKey, string> = {
  none: '1',        // 1.000 - No line height (for single-line text)
  tight: '1.272',   // 1.272 - Compact (√φ)
  normal: '1.618',  // 1.618 - Standard (φ)
  relaxed: '2.058', // 2.058 - Spacious (φ + 1/φ)
  loose: '2.618',   // 2.618 - Very spacious (φ²)
} as const;

/**
 * Type-safe line height keys
 */
export type LineHeightKeys = keyof typeof lineHeight;

/**
 * Letter spacing (tracking) scale
 *
 * Subtle adjustments based on optical balance rather than
 * strict mathematical progression, as letter spacing is
 * highly contextual to the typeface.
 */
export const letterSpacing: Record<LetterSpacingKey, string> = {
  tighter: '-0.05em',  // Very tight - for large headings
  tight: '-0.025em',   // Tight - for headings
  normal: '0',         // Normal - for body text
  wide: '0.025em',     // Wide - for small caps
  wider: '0.05em',     // Wider - for very small text
  widest: '0.08em',    // Widest - for all caps (Fib: 8)
} as const;

/**
 * Type-safe letter spacing keys
 */
export type LetterSpacingKeys = keyof typeof letterSpacing;

/**
 * Font weight scale
 * Using standard CSS values
 */
export const fontWeight = {
  thin: '100',
  extralight: '200',
  light: '300',
  normal: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
} as const;

/**
 * Typography presets for common use cases
 * Combines font size, line height, and letter spacing
 */
export const typographyPresets = {
  /**
   * Body text styles
   */
  body: {
    sm: {
      fontSize: fontSize.sm,
      lineHeight: lineHeight.relaxed,
      letterSpacing: letterSpacing.normal,
    },
    base: {
      fontSize: fontSize.base,
      lineHeight: lineHeight.normal,
      letterSpacing: letterSpacing.normal,
    },
    lg: {
      fontSize: fontSize.lg,
      lineHeight: lineHeight.normal,
      letterSpacing: letterSpacing.normal,
    },
  },

  /**
   * Heading styles
   */
  heading: {
    h1: {
      fontSize: fontSize['4xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tighter,
      fontWeight: fontWeight.bold,
    },
    h2: {
      fontSize: fontSize['3xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tighter,
      fontWeight: fontWeight.bold,
    },
    h3: {
      fontSize: fontSize['2xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tight,
      fontWeight: fontWeight.semibold,
    },
    h4: {
      fontSize: fontSize.xl,
      lineHeight: lineHeight.normal,
      letterSpacing: letterSpacing.tight,
      fontWeight: fontWeight.semibold,
    },
    h5: {
      fontSize: fontSize.lg,
      lineHeight: lineHeight.normal,
      letterSpacing: letterSpacing.normal,
      fontWeight: fontWeight.medium,
    },
    h6: {
      fontSize: fontSize.base,
      lineHeight: lineHeight.normal,
      letterSpacing: letterSpacing.normal,
      fontWeight: fontWeight.medium,
    },
  },

  /**
   * Display text (hero, landing pages)
   */
  display: {
    lg: {
      fontSize: fontSize['5xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tighter,
      fontWeight: fontWeight.extrabold,
    },
    md: {
      fontSize: fontSize['4xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tighter,
      fontWeight: fontWeight.bold,
    },
    sm: {
      fontSize: fontSize['3xl'],
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.tight,
      fontWeight: fontWeight.bold,
    },
  },

  /**
   * Utility text (labels, captions)
   */
  utility: {
    caption: {
      fontSize: fontSize.xs,
      lineHeight: lineHeight.tight,
      letterSpacing: letterSpacing.wide,
    },
    label: {
      fontSize: fontSize.sm,
      lineHeight: lineHeight.none,
      letterSpacing: letterSpacing.normal,
      fontWeight: fontWeight.medium,
    },
    overline: {
      fontSize: fontSize.xs,
      lineHeight: lineHeight.none,
      letterSpacing: letterSpacing.widest,
      fontWeight: fontWeight.semibold,
      textTransform: 'uppercase' as const,
    },
  },
} as const;

/**
 * Responsive typography scale adjustments
 * Font sizes can scale based on viewport using these multipliers
 */
export const responsiveScale = {
  mobile: 0.875,   // 87.5% of base (slightly smaller)
  tablet: 1,       // 100% of base
  desktop: 1.125,  // 112.5% of base (slightly larger)
} as const;

/**
 * Maximum line length for optimal readability
 * Based on characters per line (CPL)
 */
export const maxLineLength = {
  chars: 66,        // ~66 characters (golden ratio of comfort)
  charsNarrow: 45,  // For narrow columns
  charsWide: 80,    // For wide layouts
} as const;
